services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel
    #command: bash -c "npm run dev  & php-fpm"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5173:5173"
  nginx:
    image: nginx:alpine
    platform: linux/amd64 # Tested on Macbook Air with M1 chip
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel

  db:
    image: mariadb:10.6
    platform: linux/amd64 # Tested on Macbook Air with M1 chip
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_PASSWORD: your_mysql_password
      MYSQL_USER: laravel_user
    volumes:
      - dbdata:/var/lib/mysql/
    ports:
      - "3307:3306"
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
